import SwiftUI

extension Color {
    static let bgBlack = Color("bgBlack")
    static let bgPrimary = Color("bgPrimary")
    static let bgSecondary = Color("bgSecondary")
    static let bgDeepGreen = Color("bgDeepGreen")
    static let bgDarkGreen = Color("bgDarkGreen")
    static let bgSageGreen = Color("bgSageGreen")
    static let bgForest = Color("bgForest")
    static let bgIndigo = Color("bgIndigo")
    static let bgDarkBlue = Color("bgDarkBlue")
    static let bgNavy = Color("bgNavy")
    static let bgDarkTeal = Color("bgDarkTeal")
    static let bgTeal = Color("bgTeal")
    static let bgTealMedium = Color("bgTealMedium")

    static let primaryGreen = Color("primaryGreen")
    static let greenDark = Color("greenDark")
    static let greenDeep = Color("greenDeep")
    static let mintGreen = Color("mintGreen")

    static let accentPink = Color("accentPink")
    static let accentPurple = Color("accentPurple")
    static let accentBlue = Color("accentBlue")
    static let accentOrange = Color("accentOrange")
    static let orangeDark = Color("orangeDark")
    static let accentAmber = Color("accentAmber")
    static let amberDark = Color("amberDark")
    static let pinkLight = Color("pinkLight")
    static let accentGold = Color("accentGold")

    static let statusRed = Color("statusRed")
    static let statusRedLight = Color("statusRedLight")
    static let statusYellow = Color("statusYellow")

    static let plantGreen = Color("plantGreen")
    static let plantGreenLight = Color("plantGreenLight")
    static let plantGreenMid = Color("plantGreenMid")
    static let plantGreenDark = Color("plantGreenDark")
    static let plantGreenAccent = Color("plantGreenAccent")
    static let plantGreenPale = Color("plantGreenPale")
    static let plantLime = Color("plantLime")
    static let plantGreenMist = Color("plantGreenMist")
    static let plantGreenFog = Color("plantGreenFog")

    static let plantYellowLight = Color("plantYellowLight")
    static let plantYellow = Color("plantYellow")
    static let plantPinkLight = Color("plantPinkLight")
    static let plantPink = Color("plantPink")
    static let plantBrown = Color("plantBrown")
    static let plantBrownDark = Color("plantBrownDark")
    static let plantBrownMid = Color("plantBrownMid")
    static let plantBrownWood = Color("plantBrownWood")

    static let skyBlue = Color("skyBlue")
    static let skyBlueLight = Color("skyBlueLight")

    static let flowerRose = Color("flowerRose")
    static let flowerDaisy = Color("flowerDaisy")
    static let flowerCherry = Color("flowerCherry")
    static let flowerLavender = Color("flowerLavender")
    static let flowerHibiscus = Color("flowerHibiscus")

    static let gardenRed = Color("gardenRed")
    static let gardenPurple = Color("gardenPurple")
    static let gardenOrange = Color("gardenOrange")
    static let gardenCyan = Color("gardenCyan")
    static let gardenBlue = Color("gardenBlue")
    static let gardenPeach = Color("gardenPeach")
    static let gardenLilac = Color("gardenLilac")
    static let gardenCoral = Color("gardenCoral")
    static let gardenTeal = Color("gardenTeal")
}
